ignore: null

exclude:
  - /^contao\/languages/

mapping:
  'Andreas Isaak <info@andreas-isaak.de>': 'Andreas Isaak <andy.jared@googlemail.com>'
  'Christopher Boelter <christopher@boelter.eu>':
    - 'cogizz <c.boelter@cogizz.de>'
    - 'cboelter <christopher@boelter.eu>'
    - 'Christopher Boelter <c.boelter@cogizz.de>'
