services:
    metamodels.attribute_file.factory:
        class: MetaModels\Attribute\File\AttributeTypeFactory
        arguments:
            - "@database_connection"
            - "@metamodels.table_manipulator"
        tags:
          - { name: metamodels.attribute_factory }
