services:
    metamodels.attribute_file.factory:
        class: MetaModels\AttributeFileBundle\Attribute\AttributeTypeFactory
        arguments:
            - "@database_connection"
            - "@metamodels.table_manipulator"
            - "@contao.image.image_factory"
            - "%kernel.project_dir%"
        tags:
          - { name: metamodels.attribute_factory }

    metamodels.attribute_file.event_listener.image_size_options:
      class: MetaModels\AttributeFileBundle\Events\ImageSizeOptions
      public: true
      tags:
          -   name: kernel.event_listener
              event: dc-general.view.contao2backend.get-property-options
              method: getPropertyOptions
