services:
    metamodels.attribute_file.factory:
        class: MetaModels\AttributeFileBundle\Attribute\AttributeTypeFactory
        arguments:
            - "@database_connection"
            - "@metamodels.table_manipulator"
            - "@contao.image.image_factory"
            - "%kernel.root_dir%"
        tags:
          - { name: metamodels.attribute_factory }
